Fix cancel buttons
feedhenry-raincatcher/raincatcher-user-angular pull request #6
Opened 2017-04-21 15:18 UTC by nialldonnellyfh

# Motivation

Fixes a bug where the Cancel buttons were not bound to a function on the controller.

# Changes

- Implemented a `cancel` function in the UserFormController and GroupFormController.
- Changed the templates to use the `cancel` function

2017-04-21 15:27 UTC, ghost requested changes
Small changes required

2017-04-21 15:27 UTC, vchepeli commented on lib/worker-form/worker-form-controller.js
> +      //Otherwise, go back to the use list
Otherwise, go back to the user list

2017-04-21 15:27 UTC, vchepeli commented on lib/group-form/group-form-controller.js
> +      //Otherwise, go back to the use list
Otherwise, go back to the use list

2017-04-21 15:27 UTC, vchepeli commented on lib/group-form/group-form-controller.js
> +      $state.go('app.group');
`$state.go('app.worker');` ?

2017-04-21 15:29 UTC, nialldonnellyfh commented on lib/worker-form/worker-form-controller.js
> +      //Otherwise, go back to the use list
English is hard. Thanks

2017-04-21 15:30 UTC, nialldonnellyfh commented on lib/group-form/group-form-controller.js
> +      //Otherwise, go back to the use list
This should actually be: "Otherwise, go back to the group list"

2017-04-21 15:30 UTC, nialldonnellyfh commented on lib/group-form/group-form-controller.js
> +      $state.go('app.group');
Nope, the comment was wrong. This is the GroupFormController.

2017-04-21 15:34 UTC, ghost approved these changes

2017-04-21 15:34 UTC, vchepeli commented
LGTM

2017-04-25 07:43 UTC, wtrocki approved these changes

2017-04-25 12:04 UTC, merged